# Generated by Django 4.2.4 on 2023-08-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table=None,
        ),
    ]
